# -*- mode: ruby -*-
# vi: set ft=ruby :

box = "centos65-x86_64"

Vagrant.configure("2") do |config|

  config.vbguest.no_remote = true
  config.vbguest.auto_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  
  config.vm.define :hadoop do |node|
    node.vm.box = box
    node.vm.hostname = "hadoop.ryba"
    node.vm.network :private_network, ip: "10.10.10.2"
    node.vm.network :forwarded_port, guest: 22, host: 24001, auto_correct: true
    node.vm.provider "virtualbox" do |d|
      d.customize ["modifyvm", :id, "--memory", 5120]
      d.customize ["modifyvm", :id, "--cpus", 3]
      d.customize ["modifyvm", :id, "--ioapic", "on"]
    end
  end
end
